import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function MovieItem({ info }) {

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    {info.title}
                </h1>

                <p>Nota: {info.vote_average}</p>

                <p>{info.overview}</p>

                <img src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} alt="" width="400" />

            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export async function getServerSideProps(context) {
    const res = await fetch(`http://localhost:3000/api/movie/${context.params.id}`);

    const json = await res.json();
    console.log(json)
    return (
        {
            props: {
                info: json.info
            }
        }
    );
}
// getStaticProps // getStaticPaths => gera as páginas de antemão com os ids permitidos