import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ list }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Filmes em Destaque <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {/* <p>{props.name} </p> */}

        <Link href="/busca">Ir para a busca</Link>

        <ul>
          {list.map(item => (
            <li key={item.title}>
              <Link href={`/movie/${item.id}`}>
                <a>
                  <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} alt={`image ${item.title}`} width="150" />
                  <br />

                  {item.title}
                </a>
              </Link>
            </li>
          ))}
        </ul>

        <Link href="/sobre">Sobre</Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  // const res = await fetch('http://localhost:3000/api/hello');
  const res = await fetch('http://localhost:3000/api/trending');

  const json = await res.json();

  return (
    {
      props: {
        // name: json.name
        list: json.list
      }
    }
  );
}